### PR TITLE
🚴‍♂️ Add animation to geolocation

### LINKED ISSUE #150: Animate current location icon
**Describe the the feature request**

- See Google Maps app as an example
- Makes current location icon seem more like current location

### PR DESCRIPTION
**Pull request by SirajChokshi**
## Status:

:rocket: Ready

## Description

Adds a pulsing animation to the current location icon.

Behavior:
- Always animates inside border
- Adds animated glowing radius if heading is unavailable

Fixes #150 

## Screenshots

https://user-images.githubusercontent.com/19193347/133001537-f0be44d8-0af3-4abb-b300-a6dcd348e3a7.mov

https://user-images.githubusercontent.com/19193347/133001541-49970109-3b76-4a7b-b7c3-cdd05f6c366c.mov

### CODE REVIEW

**Comment by Qrtn** [comment]
This looks beautiful. I'm wondering, should the radius of the inner orange circle also be animated?

image

See Google Maps app on iOS, or Apple Maps.

**Comment by SirajChokshi** [comment]
> This looks beautiful. I'm wondering, should the radius of the inner orange circle also be animated?
> 
> image
> 
> See Google Maps app on iOS, or Apple Maps.

@Qrtn  Upon further observation it seems like only the inside circle is animated and the outside glow is reserved for tracking 'heading'. I'll change this PR to just animate the inner circle.

Maybe it would be useful to still have the 'breathing glow' around the geolocation pin when heading is unavailable?

**Comment by Qrtn** [comment]
image
z-index of outside glow over clusters

**Comment by Qrtn** [comment]
image

I would expect the current location marker to show up over the locations. What do you think?

**Comment by Qrtn** [comment]
There are some issues with rendering the inner circle expanding and contracting on WebKit desktop:

https://user-images.githubusercontent.com/4369024/134951793-2c1c9994-88e9-4b97-a9fa-3bf62697f42e.mov

Last thing is to fix the z-index to put the current location marker over the locations.

**Review by Qrtn — APPROVED** [review]
Beautiful!

**Pull request merged**
