### PR TITLE
🚹 Add archna's photo

### PR DESCRIPTION
**Pull request by Archna-1**

### CODE REVIEW

**Review by vasuchal — APPROVED** [review]

**Review by code-arman — COMMENTED** [review]
Do you want to add a link?

**Comment by Archna-1** [comment]
> Do you want to add a link?

Oh, wait I didn't realize we were also adding Linkedins. I'll fix that now. Thanks!

**Review by code-arman — APPROVED** [review]
lgtm

**Review by Qrtn — APPROVED** [review]
Awesome! 🚀

**Comment by Qrtn** [comment]
@Archna-1 , just a reminder for future PRs, make sure to fill out the description in the template.

**Pull request merged**
