### PR TITLE
👷🏾‍♂️ Add responsive compact nav

### LINKED ISSUE #160: Add Scaling/Compact Navigation Bar
**Describe the the feature request**
A clear and concise description of the feature.

### PR DESCRIPTION
**Pull request by SirajChokshi**
## Status:

:rocket: Ready

## Description

Adds compact version of navigation for screens smaller than 360px

Fixes #160 

## Screenshots
Demo on iPhone 5/SE screen.
Screen Shot 2021-06-06 at 2 03 13 PM

### CODE REVIEW

**Comment by Qrtn** [comment]
This looks great. Should we just go compact on all screen widths though? Would increased map real estate be valuable on all devices?

**Comment by ezwelty** [comment]
@SirajChokshi @Qrtn I think this needs to be more compact to make a difference on small devices. See my suggestions here: https://github.com/hack4impact-uiuc/falling-fruit/issues/134#issuecomment-847092211. And I agree, it may be worth making the more compact view the mobile view to avoid maintaining 3 different layouts.

This could be a good time to consider how the <add location> and <current location> buttons could be moved off the map. Probably <add location> on the right in the footer bar and <current location> on the left of the location search (like in the desktop view)?

**Comment by Qrtn** [comment]
Additional design feedback on navbar @tffnd 

- Nav should be more compact by having
  - less whitespace
  - smaller icons
  - slightly bigger text
- This will be more usable too
- See example navbars of apps on Android or iOS:
photo_2021-09-23_01-44-51
photo_2021-09-23_01-44-44
- Compare to
image
  - text size is too small
  - icons too big
  - too much whitespace above icon and below text
- Gray on navbar is too light (compare to gray in apps for iOS and Android) "not wcag compliant"

@SirajChokshi

**Comment by Qrtn** [comment]
Sorry didn't realize you already designed this. Linking here: https://www.figma.com/file/Ry8tCDzQmtpOAsKMOjuqGS/Falling-Fruit?node-id=2033%3A0

**Pull request merged**
